version: "3.7"

services:

  worker:

    build: .

    environment:

      - API_ID=${API_ID}

      - API_HASH=${API_HASH}

      - BOT_TOKEN=${BOT_TOKEN}
      
      - MDISK_TOKEN=${MDISK_TOKEN}
      
      - CUSTOM_FOOTER=${CUSTOM_FOOTER}
